/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheSide: typeof import('./components/TheSide.vue')['default']
    TheToolbox: typeof import('./components/TheToolbox.vue')['default']
  }
}
